### PR TITLE
rename to render sync

### PR DESCRIPTION
**Pull request by arthurnn**
[fixes https://github.com/chrismccord/sync/issues/215]

All tests are passing locally. The only thing I havent renamed was the views folder, I kept `app/views/sync` top level folder to make update easier, and that wont collide with the gem name changes anyways.

After this is merged, you will need to:

- [ ]  bump the version, maybe a major version
- [ ] Change the repository name
- [ ] Push to rubygems.org

cc @chrismccord @ajb @dwradcliffe

### CODE REVIEW

**Comment by ajb** [comment]
@arthurnn: Thank you!! This is fantastic.

@chrismccord: We should chat, as I'd like to get your blessing on renaming the gem. Also, if you're amenable, I think it might make sense to transfer the repository to a dedicated organization (`render_sync/render_sync`), or if there's any reason for it, my company @dobtco would be willing to sponsor the library. (Since there are no hosting costs, I'm not sure there's any reason for this.)

Feel free to ping me via email if you'd prefer.

**Comment by arthurnn** [comment]
Not sure why 193 is failing. thoughts?

**Comment by arthurnn** [comment]
Hey @ajb, it is already `May 1st, 2016` , which was the warning we put o rubygems.org to not allow `sync` as a gem name. Do you have any updates on this PR? can we get this merged, so we rename the gem name, and I can add the behavior back to rubygems.org ?

thanks a lot

**Comment by ajb** [comment]
Sorry, I've not been able to find the time, nor have I been able to make contact with @chrismccord in order to get his blessing on the name change, or to move the repo to a new organization (render_sync/render_sync).

I'm also swamped with other tasks, so I won't be able to focus on this immediately.

You can take whatever action you think is appropriate.

**Comment by chrismccord** [comment]
I am 👍 on the rename, but I don't have the bandwidth to make the code changes myself.

**Comment by arthurnn** [comment]
@ajb @chrismccord , if you wanna add me as a contributor of the gem, and I move this to the finish line, merge it, and keep an eye on issues, around it.

**Comment by chrismccord** [comment]
done!

**Comment by ajb** [comment]
Thank you for the kind offer! I'll go ahead and do that.

**Comment by ajb** [comment]
Ah, Chris beat me to it. ❤️ both

**Comment by arthurnn** [comment]
can anyone change the repository name? Thanks

**Comment by arthurnn** [comment]
https://rubygems.org/gems/render_sync new gem released.

**Comment by ajb** [comment]
🍻

**Comment by chrismccord** [comment]
Done. <3 <3 <3

**Pull request merged**
