### PR TITLE
Add SyncConfig globals + additional pusher config variables

### PR DESCRIPTION
**Pull request by ajb**
- This addresses various folks asking for Slanger support, like #113
- This closes https://github.com/chrismccord/sync/issues/195 by adding configuration variables to a `SyncConfig` global that's included on each page, instead of compiling them into the assets directly

### CODE REVIEW

**Comment by chrismccord** [comment]
> This closes #195 by adding configuration variables to a SyncConfig global that's included on each page, instead of compiling them into the assets directly

Can we cache this config lookup so we aren't mapping/rejecting/encoding on every request?

**Comment by ajb** [comment]
Yes, great idea. 

I'm gonna push `0.4.0.beta.1` to Rubygems, but it would certainly be nice to have some other folks try this out before merging. The test suite doesn't really cover this section of the library.

**Comment by aeberlin** [comment]
Encryption flag for Pusher was merged recently, FYI: https://github.com/chrismccord/sync/pull/211

**Comment by ajb** [comment]
I merged and bumped to `0.4.0`, but I'm having trouble pushing a new version of the gem.

Opened an issue on Rubygems here: https://github.com/rubygems/rubygems/issues/1474

**Comment by ajb** [comment]
Welp: https://github.com/rubygems/rubygems.org/pull/1156#issuecomment-180770630

**Pull request merged**
